import "@/styles/globals.css";

import { type Metadata } from "next";
import { PropsWithChildren } from "react";
import { Noto_Sans } from "next/font/google"


export const metadata: Metadata = {
  title: "PayMe",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const notosansFont = Noto_Sans({
  fallback: ["sans", "serif"],
  subsets: ["latin-ext"],
})


export default function RootLayout(props: PropsWithChildren) {
  return (
    <html lang="en" className={notosansFont.className}>
      <body>{props.children}</body>
    </html>
  );
}
